name: "sonar_cloud_scan_github_actions1"

on:
  push:
    branches: [ main ]

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: app/src
          args: >
              -Dsonar.organization=parin541
              -Dsonar.projectKey=python-flask-demo
              -Dsonar.python.coverage.reportPaths=coverage.xml
